export const TYPES = {
  DATABASE_SOURCE: 'DATABASE_SOURCE',
  services: {
    USER_SERVICE: 'USER_SERVICE',
    AUTH_SERVICE: 'AUTH_SERVICE',
  },
  repositories: {
    USER_REPOSITORY: 'USER_REPOSITORY',
  },
  adapters: {
    ENCRYPTION_ADAPTER: 'ENCRYPTION_ADAPTER',
    JWT_ADAPTER: 'JWT_ADAPTER',
  }
}
